### ISSUE TITLE
Read more button is broken

### ISSUE THREAD

**Issue by mahrton** [gmic/holzstock#1]
On the front page under the text
"Welcome at the Holzstocksückerklutzbonbon fansite!" when I click the Read more button I get a 404. The URL is: http://holzstock.com/node/1.html

:)

**Comment by gmic** [comment]
Op vr 3 feb. 2017 om 20:03 schreef Marton Tatai <notifications@github.com>

**Comment by gmic** [comment]
Yes, building new django site but not finished yet...
Op vr 3 feb. 2017 om 20:03 schreef Marton Tatai <notifications@github.com>

**Comment by gmic** [comment]
New site is live, no more "read more" button now...
